
export const articles = [{
  id: 1,
  name: 'Шоколадный торт с ягодами',
  pic: '/img/001.jpg',
  price: 1000,
  currency: 'RUB',
}, {
  id: 2,
  name: 'USB зарядка',
  pic: '/img/002.jpg',
  price: 1500,
  currency: 'RUB',
}, {
  id: 3,
  name: 'Флешка USB. 8 ГБ',
  pic: '/img/003.jpg',
  price: 4500,
  currency: 'RUB',
}, {
  id: 4,
  name: 'Тяпка-грабли',
  pic: '/img/004.jpg',
  price: 800,
  currency: 'RUB',
}, {
  id: 5,
  name: 'Пирожное "Корзинка с клубникой"',
  pic: '/img/005.jpg',
  price: 200,
  currency: 'RUB',
}, {
  id: 6,
  name: 'Пирожное "Печения с ягодами"',
  pic: '/img/006.jpg',
  price: 700,
  currency: 'RUB',
}, {
  id: 7,
  name: 'Большое пирожное "Печения с ягодами"',
  pic: '/img/007.jpg',
  price: 650,
  currency: 'RUB',
}, {
  id: 8,
  name: 'Пирожное "Корзинки ассорти"',
  pic: '/img/008.jpg',
  price: 650,
  currency: 'RUB',
}, {
  id: 9,
  name: 'Пирожное "Кремовые корзинки"',
  pic: '/img/009.jpg',
  price: 1500,
  currency: 'RUB',
}, {
  id: 10,
  name: 'Пирожное "Клубника с шоколадом"',
  pic: '/img/010.jpg',
  price: 855,
  currency: 'RUB',
}, {
  id: 11,
  name: 'Свекла. 1кг',
  pic: '/img/011.jpg',
  price: 50,
  currency: 'RUB',
}, {
  id: 12,
  name: 'Чайник электрический',
  pic: '/img/012.jpg',
  price: 3500,
  currency: 'RUB',
}, {
  id: 13,
  name: 'Ответка',
  pic: '/img/013.jpg',
  price: 200,
  currency: 'RUB',
}, {
  id: 14,
  name: 'Полотенце',
  pic: '/img/014.jpg',
  price: 500,
  currency: 'RUB',
}, {
  id: 15,
  name: 'Лопата',
  pic: '/img/015.jpg',
  price: 200,
  currency: 'RUB',
}, {
  id: 16,
  name: 'Колонки',
  pic: '/img/016.jpg',
  price: 750,
  currency: 'RUB',
}, {
  id: 17,
  name: 'Кофейный десерт с ягодами',
  pic: '/img/017.jpg',
  price: 350,
  currency: 'RUB',
}, {
  id: 18,
  name: 'Морковка. 1кг',
  pic: '/img/018.jpg',
  price: 70,
  currency: 'RUB',
}, {
  id: 19,
  name: 'Телевизор',
  pic: '/img/019.png',
  price: 4000,
  currency: 'RUB',
}, {
  id: 20,
  name: 'Картофель. 1кг',
  pic: '/img/020.jpg',
  price: 100,
  currency: 'RUB',
}, {
  id: 21,
  name: 'Мяч детский',
  pic: '/img/021.jpg',
  price: 400,
  currency: 'RUB',
}, {
  id: 22,
  name: 'Секатор садовй',
  pic: '/img/022.jpg',
  price: 380,
  currency: 'RUB',
}, {
  id: 23,
  name: 'Секатор садовй улучшенный',
  pic: '/img/023.jpg',
  price: 1200,
  currency: 'RUB',
}, {
  id: 24,
  name: 'Редька. 1кг',
  pic: '/img/024.jpg',
  price: 1000,
  currency: 'RUB',
}, {
  id: 25,
  name: 'Торт фруктовый',
  pic: '/img/025.jpg',
  price: 800,
  currency: 'RUB',
}, {
  id: 26,
  name: 'Столовый набор',
  pic: '/img/026.jpg',
  price: 1000,
  currency: 'RUB',
}, {
  id: 27,
  name: 'Редька зеленая. 1кг',
  pic: '/img/027.jpg',
  price: 50,
  currency: 'RUB',
}, {
  id: 28,
  name: 'Редька зеленая(местаная). 1кг',
  pic: '/img/028.jpg',
  price: 35,
  currency: 'RUB',
}, {
  id: 29,
  name: 'Лук. 1кг',
  pic: '/img/029.jpg',
  price: 70,
  currency: 'RUB',
}, {
  id: 30,
  name: 'Шоколадный торт с черникой',
  pic: '/img/030.jpg',
  price: 1000,
  currency: 'RUB',
}, {
  id: 31,
  name: 'Молоток',
  pic: '/img/031.jpg',
  price: 200,
  currency: 'RUB',
}, {
  id: 32,
  name: 'Шоколадный торт с вишней',
  pic: '/img/032.jpg',
  price: 650,
  currency: 'RUB',
}, {
  id: 33,
  name: 'Шоколадный торт с черешней',
  pic: '/img/033.jpg',
  price: 750,
  currency: 'RUB',
}, {
  id: 34,
  name: 'Секатор',
  pic: '/img/034.jpg',
  price: 550,
  currency: 'RUB',
}, {
  id: 35,
  name: 'Мыло банное',
  pic: '/img/035.jpg',
  price: 75,
  currency: 'RUB',
}, {
  id: 36,
  name: 'Хлеб бородинский',
  pic: '/img/036.jpg',
  price: 200,
  currency: 'RUB',
}, {
  id: 37,
  name: 'Свекла(местная). 1кг',
  pic: '/img/037.jpg',
  price: 45,
  currency: 'RUB',
}, {
  id: 38,
  name: 'Перчатки',
  pic: '/img/038.jpg',
  price: 150,
  currency: 'RUB',
}, {
  id: 39,
  name: 'Пирожное лимонное',
  pic: '/img/039.jpg',
  price: 250,
  currency: 'RUB',
}, {
  id: 40,
  name: 'Пирожное шолоданое с ягодами',
  pic: '/img/040.jpg',
  price: 300,
  currency: 'RUB',
}, {
  id: 41,
  name: 'Радио переносное',
  pic: '/img/041.jpg',
  price: 750,
  currency: 'RUB',
}, {
  id: 42,
  name: 'Клубничный десерт',
  pic: '/img/042.jpg',
  price: 1000,
  currency: 'RUB',
}, {
  id: 43,
  name: 'Пирожное золото и бархат',
  pic: '/img/043.jpg',
  price: 450,
  currency: 'RUB',
}, {
  id: 44,
  name: 'Пирожное "Победитель"',
  pic: '/img/044.jpg',
  price: 350,
  currency: 'RUB',
}];

export default articles;
